name: Build documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: robotics-course
      package_name: robotics-course
      path_to_docs: robotics-course/units/
      additional_args: --not_python_module
      languages: en
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
